services:
  mariadb:
    build: ./mariadb
    container_name: mariadb
    restart: on-failure
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    expose:
      - "3306"
    ports:
      - "3306:3306"
    entrypoint: "/tmp/entrypoint.sh"
    command: ["mysqld", "--bind-address=0.0.0.0", "--user=mysql"]

  nginx:
    build: ./nginx
    container_name: nginx
    restart: on-failure
    depends_on:
      - wordpress
    volumes:
      - nginx:/etc/nginx
    networks:
      - inception
    entrypoint: "/tmp/entrypoint.sh"
    command: ["nginx", "-g", "daemon off;"]

  wordpress:
    build: ./wordpress
    container_name: wordpress
    restart: on-failure
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    depends_on:
      - mariadb
    expose:
      - "80"
      - "443"
    ports:
      - "80:80"
      - "443:443"
    entrypoint: "/tmp/entrypoint.sh"
    command: ["/usr/sbin/php-fpm82", "-F"]

networks:
  inception:
    driver: bridge

volumes:
  mariadb:
    driver: local
    driver_opts:
        type: none
        device: ${DATADIR}/mariadb
        o: bind

  nginx:
    driver: local
    driver_opts:
      type: none
      device: ${DATADIR}/nginx
      o: bind

  wordpress:
    driver: local
    driver_opts:
      type: none
      device: ${DATADIR}/wordpress
      o: bind
