services:
  mariadb:
    build: ./mariadb
    container_name: mariadb
    restart: on-failure
    env_file:
      - .env
    volumes:
      - ${DATADIR}/mariadb:/var/lib/mysql
    networks:
      - inception
    ports:
      - "3306:3306"
    entrypoint: "/usr/sbin/entrypoint.sh"
    command: ["mysqld"]

  nginx:
    build: ./nginx
    container_name: nginx
    hostname: ${WP_URL}
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - wordpress
    networks:
      - inception
    expose:
      - "443"
    ports:
      - "443:443"
    entrypoint: "/tmp/entrypoint.sh"
    command: ["nginx-debug", "-g", "daemon off;"]

  wordpress:
    build: ./wordpress
    container_name: wordpress
    restart: on-failure
    env_file:
      - .env
    volumes:
      - ${DATADIR}/wordpress:/var/www/html/wordpress
    networks:
      - inception
    depends_on:
      - mariadb
    ports:
      - "9000:9000"
    entrypoint: "/tmp/entrypoint.sh"
    command: ["/usr/sbin/php-fpm82", "-F"]

networks:
  inception:
    driver: bridge

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: ${DATADIR}/mariadb
      o: bind
